# Generated by Django 3.1.5 on 2021-01-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeekysDesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='token_time',
            field=models.TimeField(default=''),
        ),
    ]
