# Generated by Django 3.1.5 on 2021-01-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeekysDesk', '0002_subscriber_token_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='token_time',
            field=models.TimeField(default=1611291406.501016),
        ),
    ]
