# Generated by Django 3.1.5 on 2021-01-22 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeekysDesk', '0006_auto_20210122_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='token_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
