# Generated by Django 3.1.5 on 2021-01-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeekysDesk', '0014_auto_20210122_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='token_time',
            field=models.TimeField(default='25:50:00'),
        ),
    ]
