# Generated by Django 3.1.5 on 2021-01-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeekysDesk', '0015_auto_20210122_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='token_time',
            field=models.TimeField(default='12:00 AM'),
        ),
    ]
