# Generated by Django 3.1.5 on 2021-01-22 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeekysDesk', '0016_auto_20210122_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='token_time',
        ),
    ]
