# Generated by Django 3.1.5 on 2021-01-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeekysDesk', '0017_remove_subscriber_token_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='token_time',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
