# Generated by Django 3.1.5 on 2021-01-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeekysDesk', '0019_auto_20210123_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='token_time',
        ),
    ]
