# Generated by Django 3.1.5 on 2021-01-23 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GeekysDesk', '0020_remove_subscriber_token_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='token_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
