# Generated by Django 3.1.5 on 2021-01-23 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeekysDesk', '0021_subscriber_token_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='token_time',
        ),
    ]
