# Generated by Django 3.1.5 on 2021-02-19 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeekysDesk', '0024_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image_alternative_text',
        ),
    ]
