# Generated by Django 3.1.5 on 2021-02-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeekysDesk', '0030_post_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/Category/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='feature_image',
            field=models.ImageField(default='', upload_to='img/Post/'),
        ),
    ]
