# Generated by Django 3.1.5 on 2021-02-22 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeekysDesk', '0031_auto_20210220_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='feature_to_home_page',
            new_name='show_to_main_menu',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='feature_to_home_page',
            new_name='feature_to_editors_pick',
        ),
    ]
