# Generated by Django 3.1.5 on 2021-02-25 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeekysDesk', '0034_auto_20210225_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_subject',
        ),
    ]
