# Generated by Django 3.1.5 on 2021-01-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site_Icon', models.ImageField(upload_to='img/')),
                ('Site_Logo', models.ImageField(upload_to='img/')),
                ('Site_Name', models.CharField(blank=True, max_length=255)),
                ('Site_Short_About_Info', models.TextField(default='')),
            ],
        ),
    ]
