# Generated by Django 3.1.5 on 2021-01-20 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSettings', '0003_socialmediasettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialMediaSettings',
            new_name='SocialMediaSetting',
        ),
    ]
