# Generated by Django 3.1.5 on 2021-02-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSettings', '0009_delete_importantlinksetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprotantLinkSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Page_Name', models.CharField(max_length=255)),
            ],
        ),
    ]
