# Generated by Django 3.1.5 on 2021-02-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSettings', '0010_improtantlinksetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='improtantlinksetting',
            name='Page_url_link',
            field=models.CharField(choices=[(0, 'home'), (1, 'subscribe-to-newsletter'), (2, 'subscription-confirmation'), (3, 'unsubscribe'), (4, 'logout'), (5, 'login')], default='home', max_length=100),
        ),
    ]
