# Generated by Django 3.1.5 on 2021-02-08 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSettings', '0011_improtantlinksetting_page_url_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImprotantLinkSetting',
        ),
    ]
