# Generated by Django 3.1.5 on 2021-02-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSettings', '0012_delete_improtantlinksetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantLinkSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Page_Name', models.CharField(max_length=100)),
                ('Page_Url', models.CharField(choices=[(0, 'index'), (1, 'login'), (2, 'logout'), (3, 'password_change'), (4, 'password_change_done'), (5, 'jsi18n'), (6, 'view_on_site'), (7, 'home'), (8, 'subscribe-to-newsletter'), (9, 'subscription-confirmation'), (10, 'unsubscribe'), (11, 'logout'), (12, 'login')], default='home', max_length=255)),
            ],
        ),
    ]
