# Generated by Django 3.1.5 on 2021-02-08 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSettings', '0013_importantlinksetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportantLinkSetting',
        ),
    ]
