# Generated by Django 3.1.5 on 2021-02-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSettings', '0014_delete_importantlinksetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicsetting',
            name='Site_Icon',
            field=models.ImageField(upload_to='img/Site/'),
        ),
        migrations.AlterField(
            model_name='basicsetting',
            name='Site_Logo',
            field=models.ImageField(upload_to='img/Site/'),
        ),
    ]
