# Generated by Django 3.1.5 on 2021-01-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSettings', '0002_contactsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Social_Media_Name', models.CharField(max_length=50)),
                ('Font_Awesome_Class_For_Icon', models.CharField(help_text='Ex -  fa fa-facebook', max_length=100)),
                ('Social_Media_Link', models.TextField(default='')),
            ],
        ),
    ]
