# Generated by Django 3.1.5 on 2021-03-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSettings', '0015_auto_20210220_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicSEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Home_Page_Meta_Keyword', models.TextField(default='')),
                ('Home_Page_Meta_Description', models.TextField(default='')),
                ('About_Page_Meta_Keyword', models.TextField(default='')),
                ('About_Page_Meta_Description', models.TextField(default='')),
                ('Contact_Page_Meta_Keyword', models.TextField(default='')),
                ('Contact_Page_Meta_Description', models.TextField(default='')),
            ],
        ),
    ]
